default:
  golem_name: shareIBC
  golem_version: 0.0.0.9000
  app_prod: no
  posts_path: posts/development/DT_POSTS_DEV
  mailing_list_path: mailing_list/DT_MAILING_LIST_DEV
  app_url: http://127.0.0.1:3838
  gmail_account: share.ibcmadrid@gmail.com
  ibc_url: https://ibcmadrid.com/
  ibc_building_url: https://lh3.googleusercontent.com/d/1nbW-IYdtXoqzBosvgMmR5MY1Ij4faZph
  ibc_logo_url: https://lh3.googleusercontent.com/d/1-ojsCffeIsTovPBTBC_SKPP8CL76SoHL
production:
  app_prod: yes
  posts_path: posts/production/DT_POSTS
  mailing_list_path: mailing_list/DT_MAILING_LIST
  app_url: https://ibcmadrid.com/shareIBC
dev:
  golem_wd: !expr here::here()
